library analysis.errors;

import 'dart:async';

import 'package:logging/logging.dart';

import 'atom.dart' show Directory, File;
import 'utils.dart';
import 'impl/analysis_server_gen.dart' show AnalysisErrors, AnalysisError,
  AnalysisFlushResults;

final Logger _logger = new Logger('error_repository');

/// Repository of errors generated by `analysis.errors` events
///
/// One-stop shop for getting the status of errors the analyzer has reported.
/// Source agonostic.
class ErrorRepository implements Disposable {
  /// A collection of all known errors that the analysis_server has provided us,
  /// organized by filename.
  final Map<String, List<AnalysisError>> knownErrors = {};

  final StreamSubscriptions subs = new StreamSubscriptions();

  StreamController _controller = new StreamController.broadcast();
  Stream<AnalysisErrors> _errorStream;
  Stream<AnalysisFlushResults> _flushStream;

  ErrorRepository();

  // TODO: stream a delta object like dart-tools ErrorRepository does.
  Stream get onChange => _controller.stream;

  void initStreams(Stream<AnalysisErrors> errorStream,
      Stream<AnalysisFlushResults> flushStream) {
    this._errorStream = errorStream;
    this._flushStream = flushStream;

    subs.cancel();

    subs.add(_errorStream.listen(_handleAddErrors));
    subs.add(_flushStream.listen(_handleFlushErrors));
  }

  /// Clear all known errors. This is useful for situations like when the
  /// analysis server goes down.
  void clearAll() {
    knownErrors.clear();
    _controller.add(null);
  }

  /// Clear all errors for files contained within the given directory.
  void clearForDirectory(Directory dir) {
    List<String> paths = knownErrors.keys.toList();
    for (String path in paths) {
      if (dir.contains(path)) knownErrors.remove(path);
    }
  }

  void dispose() => subs.cancel();

  void _handleAddErrors(AnalysisErrors analysisErrors) {
    String path = analysisErrors.file;
    File file = new File.fromPath(path);
    if (file.existsSync()) {
      knownErrors[path] = analysisErrors.errors;
      _controller.add(null);
    } else {
      _logger.info('received an error event for a non-existent file: ${path}');
    }
  }

  void _handleFlushErrors(AnalysisFlushResults analysisFlushResults) {
    analysisFlushResults.files.forEach(knownErrors.remove);
    _controller.add(null);
  }
}
